# Generated by Django 5.2.11 on 2026-04-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=120)),
                ('direccion', models.CharField(choices=[('entrada', 'entrada'), ('salida', 'salida')], max_length=20)),
                ('sistema_origen', models.CharField(default='unknown', max_length=120)),
                ('sistema_destino', models.CharField(blank=True, max_length=120, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('metodo', models.CharField(default='POST', max_length=10)),
                ('request_json', models.JSONField(default=dict)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('exitoso', 'exitoso'), ('fallido', 'fallido')], default='pendiente', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
